name: CI Docker Build

# 1. Quando essa esteira vai rodar?
# Resposta: Toda vez que houver um 'push' na linha principal (main)
on:
  push:
    branches: ["main"]

# 2. O que ela vai fazer?
jobs:
  build-teste:
    # 3. Qual "computador" o GitHub vai nos emprestar de graça para rodar isso?
    runs-on: ubuntu-latest

    # 4. O passo a passo (Steps)
    steps:
      # Passo A: O robô entra na sua máquina virtual e baixa o seu código do repositório
      - name: Pegar o código do repositório (Checkout)
        uses: actions/checkout@v4

      # Passo B: O robô roda o MESMO comando de build que você rodou na sua máquina hoje cedo
      - name: Testar a construção da Imagem Docker
        run: docker build -t teste-api-flask .
