name: CI/CD Docker Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Pegar o código do repositório
        uses: actions/checkout@v4

      - name: 2. Fazer Login no Docker Hub
        # Aqui o robô usa os segredos que guardamos no cofre!
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 3. Construir e Enviar a Imagem (Build & Push)
        # Aqui ele constrói a imagem já com a etiqueta do seu usuário e manda pra nuvem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minha-api-flask:latest
